config/routes.rb
Rails.application.routes.draw do
  resources :lumberjills

  resources :lumberjacks

  root 'welcome#home'
  get 'welcome/home'
  get 'welcome/about'
end

app/models/hot.rb
class Hot < ActiveRecord::Base
  belongs_to :lumberjack
  belongs_to :lumberjill
end

app/models/lumberjack.rb
class Lumberjack < ActiveRecord::Base
  belongs_to :lumberjill
  has_many :lumberjills


  has_and_belongs_to_many :hotties, class_name: 'Lumberjill'
end

app/models/lumberjill.rb
class Lumberjill < ActiveRecord::Base
  belongs_to :lumberjack
  has_many :lumberjacks

  has_many :hots
  has_many :hotties, through: :hots, source: :lumberjack
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lumberjacks_controller.rb
class LumberjacksController < ApplicationController
  before_action :set_lumberjack, only: [:show, :edit, :update, :destroy]

  # GET /lumberjacks
  # GET /lumberjacks.json
  def index
    @lumberjacks = Lumberjack.all
  end

  # GET /lumberjacks/1
  # GET /lumberjacks/1.json
  def show
  end

  # GET /lumberjacks/new
  def new
    @lumberjack = Lumberjack.new
  end

  # GET /lumberjacks/1/edit
  def edit
  end

  # POST /lumberjacks
  # POST /lumberjacks.json
  def create
    @lumberjack = Lumberjack.new(lumberjack_params)

    respond_to do |format|
      if @lumberjack.save
        format.html { redirect_to @lumberjack, notice: 'Lumberjack was successfully created.' }
        format.json { render :show, status: :created, location: @lumberjack }
      else
        format.html { render :new }
        format.json { render json: @lumberjack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lumberjacks/1
  # PATCH/PUT /lumberjacks/1.json
  def update
    respond_to do |format|
      if @lumberjack.update(lumberjack_params)
        format.html { redirect_to @lumberjack, notice: 'Lumberjack was successfully updated.' }
        format.json { render :show, status: :ok, location: @lumberjack }
      else
        format.html { render :edit }
        format.json { render json: @lumberjack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lumberjacks/1
  # DELETE /lumberjacks/1.json
  def destroy
    @lumberjack.destroy
    respond_to do |format|
      format.html { redirect_to lumberjacks_url, notice: 'Lumberjack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lumberjack
      @lumberjack = Lumberjack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lumberjack_params
      params.require(:lumberjack).permit(:name, :lumberjill_id, :the_one_id)
    end
end

app/controllers/lumberjills_controller.rb
class LumberjillsController < ApplicationController
  before_action :set_lumberjill, only: [:show, :edit, :update, :destroy]

  # GET /lumberjills
  # GET /lumberjills.json
  def index
    @lumberjills = Lumberjill.all
  end

  # GET /lumberjills/1
  # GET /lumberjills/1.json
  def show
  end

  # GET /lumberjills/new
  def new
    @lumberjill = Lumberjill.new
  end

  # GET /lumberjills/1/edit
  def edit
  end

  # POST /lumberjills
  # POST /lumberjills.json
  def create
    @lumberjill = Lumberjill.new(lumberjill_params)

    respond_to do |format|
      if @lumberjill.save
        format.html { redirect_to @lumberjill, notice: 'Lumberjill was successfully created.' }
        format.json { render :show, status: :created, location: @lumberjill }
      else
        format.html { render :new }
        format.json { render json: @lumberjill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lumberjills/1
  # PATCH/PUT /lumberjills/1.json
  def update
    respond_to do |format|
      if @lumberjill.update(lumberjill_params)
        format.html { redirect_to @lumberjill, notice: 'Lumberjill was successfully updated.' }
        format.json { render :show, status: :ok, location: @lumberjill }
      else
        format.html { render :edit }
        format.json { render json: @lumberjill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lumberjills/1
  # DELETE /lumberjills/1.json
  def destroy
    @lumberjill.destroy
    respond_to do |format|
      format.html { redirect_to lumberjills_url, notice: 'Lumberjill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lumberjill
      @lumberjill = Lumberjill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lumberjill_params
      params.require(:lumberjill).permit(:name, :lumberjack_id, :the_one_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lumberjacks_helper.rb
module LumberjacksHelper
end

app/helpers/lumberjills_helper.rb
module LumberjillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Timber', root_path, class: "navbar-brand" %>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Lumberjacks", lumberjacks_path %></li>
        <li><%= link_to "Lumberjills", lumberjills_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class='background-image'></div>
    <div class='container'>
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lumberjacks/_form.html.erb
<%= simple_form_for(@lumberjack) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :lumberjill %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lumberjacks/edit.html.erb
<h1>Editing lumberjack</h1>

<%= render 'form' %>

<%= link_to 'Show', @lumberjack %> |
<%= link_to 'Back', lumberjacks_path %>

app/views/lumberjacks/index.html.erb
<h1>Listing lumberjacks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>True Love</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lumberjacks.each do |lumberjack| %>
      <tr>
        <td><%= lumberjack.name %></td>
        <td><%= lumberjack.lumberjill ? lumberjack.lumberjill.name : "nil" %></td>
        <td><%= link_to 'Show', lumberjack %></td>
        <td><%= link_to 'Edit', edit_lumberjack_path(lumberjack) %></td>
        <td><%= link_to 'Destroy', lumberjack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lumberjack', new_lumberjack_path %>

app/views/lumberjacks/new.html.erb
<h1>New lumberjack</h1>

<%= render 'form' %>

<%= link_to 'Back', lumberjacks_path %>

app/views/lumberjacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lumberjack.name %>
</p>

<p>
  <strong>True Love:</strong>
  <%= @lumberjack.lumberjill ? @lumberjack.lumberjill.name : "nil" %>
</p>

<p>
  <strong>Admirers:</strong>
  <% @lumberjack.lumberjills.each do |lumberjill| %>
  <%= lumberjill.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_lumberjack_path(@lumberjack) %> |
<%= link_to 'Back', lumberjacks_path %>

app/views/lumberjills/_form.html.erb
<%= simple_form_for(@lumberjill) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :lumberjack %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lumberjills/edit.html.erb
<h1>Editing lumberjill</h1>

<%= render 'form' %>

<%= link_to 'Show', @lumberjill %> |
<%= link_to 'Back', lumberjills_path %>

app/views/lumberjills/index.html.erb
<h1>Listing lumberjills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>True Love</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lumberjills.each do |lumberjill| %>
      <tr>
        <td><%= lumberjill.name %></td>
        <td><%= lumberjill.lumberjack ? lumberjill.lumberjack.name : "nil" %></td>
        <td><%= link_to 'Show', lumberjill %></td>
        <td><%= link_to 'Edit', edit_lumberjill_path(lumberjill) %></td>
        <td><%= link_to 'Destroy', lumberjill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lumberjill', new_lumberjill_path %>

app/views/lumberjills/new.html.erb
<h1>New lumberjill</h1>

<%= render 'form' %>

<%= link_to 'Back', lumberjills_path %>

app/views/lumberjills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lumberjill.name %>
</p>

<p>
  <strong>True Love:</strong>
  <%= @lumberjill.lumberjack ? @lumberjill.lumberjack.name : "nil" %>
</p>

<p>
  <strong>Admirers:</strong>
  <% @lumberjill.lumberjacks.each do |lumberjack| %>
  <%= lumberjack.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_lumberjill_path(@lumberjill) %> |
<%= link_to 'Back', lumberjills_path %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/home.html.erb
<h1>Timber</h1>
<p>Find me in app/views/welcome/home.html.erb</p>